sudo: required
services: 
  - docker

before_install:
  - docker build -t jonogeorge/docker_react -f Dockerfile.dev .

script:
  - docker run jonogeorge/docker_react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app:  "docker-react-test"
  env:  "DockerReactTest-env"
  bucket_name: "elasticbeanstalk-us-east-1-945579007350"
  bucket_path: "docker-react-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"  
